// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2022-03-07T13:16:17+01:00
// using data from https://www.wikidata.org
package iso3166

import (
	"golang.org/x/text/language"
	"strings"

	"github.com/knakk/sirkulator/internal/localizer"
	"github.com/knakk/sirkulator/vocab"
)

//go:generate go run gen_alpha2.go
//go:generate go fmt alpha2.go

// Country is an ISO 3166-1 two-letter code, maintained by ublished by the International Organization
// for Standardization (ISO), to represent countries, dependent territories, and special areas of
// geographical interest.
// https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
type Country string

const (
	AD Country = "AD"
	AE Country = "AE"
	AF Country = "AF"
	AG Country = "AG"
	AI Country = "AI"
	AL Country = "AL"
	AM Country = "AM"
	AO Country = "AO"
	AQ Country = "AQ"
	AR Country = "AR"
	AS Country = "AS"
	AT Country = "AT"
	AU Country = "AU"
	AW Country = "AW"
	AX Country = "AX"
	AZ Country = "AZ"
	BA Country = "BA"
	BB Country = "BB"
	BD Country = "BD"
	BE Country = "BE"
	BF Country = "BF"
	BG Country = "BG"
	BH Country = "BH"
	BI Country = "BI"
	BJ Country = "BJ"
	BL Country = "BL"
	BM Country = "BM"
	BN Country = "BN"
	BO Country = "BO"
	BQ Country = "BQ"
	BR Country = "BR"
	BS Country = "BS"
	BT Country = "BT"
	BV Country = "BV"
	BW Country = "BW"
	BY Country = "BY"
	BZ Country = "BZ"
	CA Country = "CA"
	CC Country = "CC"
	CD Country = "CD"
	CF Country = "CF"
	CG Country = "CG"
	CH Country = "CH"
	CI Country = "CI"
	CK Country = "CK"
	CL Country = "CL"
	CM Country = "CM"
	CN Country = "CN"
	CO Country = "CO"
	CR Country = "CR"
	CU Country = "CU"
	CV Country = "CV"
	CW Country = "CW"
	CX Country = "CX"
	CY Country = "CY"
	CZ Country = "CZ"
	DE Country = "DE"
	DG Country = "DG"
	DJ Country = "DJ"
	DK Country = "DK"
	DM Country = "DM"
	DO Country = "DO"
	DZ Country = "DZ"
	EA Country = "EA"
	EC Country = "EC"
	EE Country = "EE"
	EG Country = "EG"
	EH Country = "EH"
	ER Country = "ER"
	ES Country = "ES"
	ET Country = "ET"
	FI Country = "FI"
	FJ Country = "FJ"
	FK Country = "FK"
	FM Country = "FM"
	FO Country = "FO"
	FR Country = "FR"
	GA Country = "GA"
	GB Country = "GB"
	GD Country = "GD"
	GE Country = "GE"
	GF Country = "GF"
	GG Country = "GG"
	GH Country = "GH"
	GI Country = "GI"
	GL Country = "GL"
	GM Country = "GM"
	GN Country = "GN"
	GP Country = "GP"
	GQ Country = "GQ"
	GR Country = "GR"
	GS Country = "GS"
	GT Country = "GT"
	GU Country = "GU"
	GW Country = "GW"
	GY Country = "GY"
	HK Country = "HK"
	HM Country = "HM"
	HN Country = "HN"
	HR Country = "HR"
	HT Country = "HT"
	HU Country = "HU"
	ID Country = "ID"
	IE Country = "IE"
	IL Country = "IL"
	IM Country = "IM"
	IN Country = "IN"
	IO Country = "IO"
	IQ Country = "IQ"
	IR Country = "IR"
	IS Country = "IS"
	IT Country = "IT"
	JE Country = "JE"
	JM Country = "JM"
	JO Country = "JO"
	JP Country = "JP"
	KE Country = "KE"
	KG Country = "KG"
	KH Country = "KH"
	KI Country = "KI"
	KM Country = "KM"
	KN Country = "KN"
	KP Country = "KP"
	KR Country = "KR"
	KW Country = "KW"
	KY Country = "KY"
	KZ Country = "KZ"
	LA Country = "LA"
	LB Country = "LB"
	LC Country = "LC"
	LI Country = "LI"
	LK Country = "LK"
	LR Country = "LR"
	LS Country = "LS"
	LT Country = "LT"
	LU Country = "LU"
	LV Country = "LV"
	LY Country = "LY"
	MA Country = "MA"
	MC Country = "MC"
	MD Country = "MD"
	ME Country = "ME"
	MF Country = "MF"
	MG Country = "MG"
	MH Country = "MH"
	MK Country = "MK"
	ML Country = "ML"
	MM Country = "MM"
	MN Country = "MN"
	MO Country = "MO"
	MP Country = "MP"
	MQ Country = "MQ"
	MR Country = "MR"
	MS Country = "MS"
	MT Country = "MT"
	MU Country = "MU"
	MV Country = "MV"
	MW Country = "MW"
	MX Country = "MX"
	MY Country = "MY"
	MZ Country = "MZ"
	NA Country = "NA"
	NC Country = "NC"
	NE Country = "NE"
	NF Country = "NF"
	NG Country = "NG"
	NI Country = "NI"
	NL Country = "NL"
	NO Country = "NO"
	NP Country = "NP"
	NR Country = "NR"
	NU Country = "NU"
	NZ Country = "NZ"
	OM Country = "OM"
	PA Country = "PA"
	PE Country = "PE"
	PF Country = "PF"
	PG Country = "PG"
	PH Country = "PH"
	PK Country = "PK"
	PL Country = "PL"
	PM Country = "PM"
	PN Country = "PN"
	PR Country = "PR"
	PS Country = "PS"
	PT Country = "PT"
	PW Country = "PW"
	PY Country = "PY"
	QA Country = "QA"
	RE Country = "RE"
	RO Country = "RO"
	RS Country = "RS"
	RU Country = "RU"
	RW Country = "RW"
	SA Country = "SA"
	SB Country = "SB"
	SC Country = "SC"
	SD Country = "SD"
	SE Country = "SE"
	SG Country = "SG"
	SH Country = "SH"
	SI Country = "SI"
	SJ Country = "SJ"
	SK Country = "SK"
	SL Country = "SL"
	SM Country = "SM"
	SN Country = "SN"
	SO Country = "SO"
	SR Country = "SR"
	SS Country = "SS"
	ST Country = "ST"
	SV Country = "SV"
	SX Country = "SX"
	SY Country = "SY"
	SZ Country = "SZ"
	TC Country = "TC"
	TD Country = "TD"
	TF Country = "TF"
	TG Country = "TG"
	TH Country = "TH"
	TJ Country = "TJ"
	TK Country = "TK"
	TL Country = "TL"
	TM Country = "TM"
	TN Country = "TN"
	TO Country = "TO"
	TR Country = "TR"
	TT Country = "TT"
	TV Country = "TV"
	TW Country = "TW"
	TZ Country = "TZ"
	UA Country = "UA"
	UG Country = "UG"
	UM Country = "UM"
	US Country = "US"
	UY Country = "UY"
	UZ Country = "UZ"
	VA Country = "VA"
	VC Country = "VC"
	VE Country = "VE"
	VG Country = "VG"
	VI Country = "VI"
	VN Country = "VN"
	VU Country = "VU"
	WF Country = "WF"
	WS Country = "WS"
	XK Country = "XK"
	YE Country = "YE"
	YT Country = "YT"
	YU Country = "YU"
	ZA Country = "ZA"
	ZM Country = "ZM"
	ZW Country = "ZW"
)

var alpha2Labels = map[Country][2]string{
	AD: {"Andorra", "Andorra"},
	AE: {"United Arab Emirates", "De forente arabiske emirater"},
	AF: {"Afghanistan", "Afghanistan"},
	AG: {"Antigua and Barbuda", "Antigua og Barbuda"},
	AI: {"Anguilla", "Anguilla"},
	AL: {"Albania", "Albania"},
	AM: {"Armenia", "Armenia"},
	AO: {"Angola", "Angola"},
	AQ: {"Antarctic Treaty area", "Antarktistraktatsområdet"},
	AR: {"Argentina", "Argentina"},
	AS: {"American Samoa", "Amerikansk Samoa"},
	AT: {"Austria", "Østerrike"},
	AU: {"Australia", "Australia"},
	AW: {"Aruba", "Aruba"},
	AX: {"Åland", "Åland"},
	AZ: {"Azerbaijan", "Aserbajdsjan"},
	BA: {"Bosnia and Herzegovina", "Bosnia-Hercegovina"},
	BB: {"Barbados", "Barbados"},
	BD: {"Bangladesh", "Bangladesh"},
	BE: {"Belgium", "Belgia"},
	BF: {"Burkina Faso", "Burkina Faso"},
	BG: {"Bulgaria", "Bulgaria"},
	BH: {"Bahrain", "Bahrain"},
	BI: {"Burundi", "Burundi"},
	BJ: {"Benin", "Benin"},
	BL: {"Saint Barthélemy", "Saint-Barthélemy"},
	BM: {"Bermuda", "Bermuda"},
	BN: {"Brunei", "Brunei"},
	BO: {"Bolivia", "Bolivia"},
	BQ: {"Caribbean Netherlands", "Karibisk Nederland"},
	BR: {"Brazil", "Brasil"},
	BS: {"The Bahamas", "Bahamas"},
	BT: {"Bhutan", "Bhutan"},
	BV: {"Bouvet Island", "Bouvetøya"},
	BW: {"Botswana", "Botswana"},
	BY: {"Belarus", "Hviterussland"},
	BZ: {"Belize", "Belize"},
	CA: {"Canada", "Canada"},
	CC: {"Cocos (Keeling) Islands", "Kokosøyene"},
	CD: {"Democratic Republic of the Congo", "Den demokratiske republikken Kongo"},
	CF: {"Central African Republic", "Den sentralafrikanske republikk"},
	CG: {"Republic of the Congo", "Republikken Kongo"},
	CH: {"Switzerland", "Sveits"},
	CI: {"Côte d'Ivoire", "Elfenbenskysten"},
	CK: {"Cook Islands", "Cookøyene"},
	CL: {"Chile", "Chile"},
	CM: {"Cameroon", "Kamerun"},
	CN: {"People's Republic of China", "Kina"},
	CO: {"Colombia", "Colombia"},
	CR: {"Costa Rica", "Costa Rica"},
	CU: {"Cuba", "Cuba"},
	CV: {"Cape Verde", "Kapp Verde"},
	CW: {"Curaçao", "Curaçao"},
	CX: {"Christmas Island", "Christmasøya"},
	CY: {"Cyprus", "Kypros"},
	CZ: {"Czech Republic", "Tsjekkia"},
	DE: {"Germany", "Tyskland"},
	DG: {"Diego Garcia", "Diego Garcia"},
	DJ: {"Djibouti", "Djibouti"},
	DK: {"Denmark", "Danmark"},
	DM: {"Dominica", "Dominica"},
	DO: {"Dominican Republic", "Den dominikanske republikk"},
	DZ: {"Algeria", "Algerie"},
	EA: {"Ceuta and Melilla", "Ceuta og Melilla"},
	EC: {"Ecuador", "Ecuador"},
	EE: {"Estonia", "Estland"},
	EG: {"Egypt", "Egypt"},
	EH: {"Western Sahara", "Vest-Sahara"},
	ER: {"Eritrea", "Eritrea"},
	ES: {"Spain", "Spania"},
	ET: {"Ethiopia", "Etiopia"},
	FI: {"Finland", "Finland"},
	FJ: {"Fiji", "Fiji"},
	FK: {"Falkland Islands", "Falklandsøyene"},
	FM: {"Federated States of Micronesia", "Mikronesiaføderasjonen"},
	FO: {"Faroe Islands", "Færøyene"},
	FR: {"France", "Frankrike"},
	GA: {"Gabon", "Gabon"},
	GB: {"United Kingdom", "Storbritannia"},
	GD: {"Grenada", "Grenada"},
	GE: {"Georgia", "Georgia"},
	GF: {"French Guiana", "Fransk Guyana"},
	GG: {"Guernsey", "Guernsey"},
	GH: {"Ghana", "Ghana"},
	GI: {"Gibraltar", "Gibraltar"},
	GL: {"Greenland", "Grønland"},
	GM: {"The Gambia", "Gambia"},
	GN: {"Guinea", "Guinea"},
	GP: {"Guadeloupe", "Guadeloupe"},
	GQ: {"Equatorial Guinea", "Ekvatorial-Guinea"},
	GR: {"Greece", "Hellas"},
	GS: {"South Georgia and the South Sandwich Islands", "Sør-Georgia og Sør-Sandwichøyene"},
	GT: {"Guatemala", "Guatemala"},
	GU: {"Guam", "Guam"},
	GW: {"Guinea-Bissau", "Guinea-Bissau"},
	GY: {"Guyana", "Guyana"},
	HK: {"Hong Kong", "Hongkong"},
	HM: {"Heard Island and McDonald Islands", "Heard- og McDonaldøyene"},
	HN: {"Honduras", "Honduras"},
	HR: {"Croatia", "Kroatia"},
	HT: {"Haiti", "Haiti"},
	HU: {"Hungary", "Ungarn"},
	ID: {"Indonesia", "Indonesia"},
	IE: {"Republic of Ireland", "Irland"},
	IL: {"Israel", "Israel"},
	IM: {"Isle of Man", "Man"},
	IN: {"India", "India"},
	IO: {"British Indian Ocean Territory", "Det britiske territoriet i Indiahavet"},
	IQ: {"Iraq", "Irak"},
	IR: {"Iran", "Iran"},
	IS: {"Iceland", "Island"},
	IT: {"Italy", "Italia"},
	JE: {"Jersey", "Jersey"},
	JM: {"Jamaica", "Jamaica"},
	JO: {"Jordan", "Jordan"},
	JP: {"Japan", "Japan"},
	KE: {"Kenya", "Kenya"},
	KG: {"Kyrgyzstan", "Kirgisistan"},
	KH: {"Cambodia", "Kambodsja"},
	KI: {"Kiribati", "Kiribati"},
	KM: {"Comoros", "Komorene"},
	KN: {"Saint Kitts and Nevis", "Saint Kitts og Nevis"},
	KP: {"North Korea", "Nord-Korea"},
	KR: {"South Korea", "Sør-Korea"},
	KW: {"Kuwait", "Kuwait"},
	KY: {"Cayman Islands", "Caymanøyene"},
	KZ: {"Kazakhstan", "Kasakhstan"},
	LA: {"Laos", "Laos"},
	LB: {"Lebanon", "Libanon"},
	LC: {"Saint Lucia", "Saint Lucia"},
	LI: {"Liechtenstein", "Liechtenstein"},
	LK: {"Sri Lanka", "Sri Lanka"},
	LR: {"Liberia", "Liberia"},
	LS: {"Lesotho", "Lesotho"},
	LT: {"Lithuania", "Litauen"},
	LU: {"Luxembourg", "Luxembourg"},
	LV: {"Latvia", "Latvia"},
	LY: {"Libya", "Libya"},
	MA: {"Morocco", "Marokko"},
	MC: {"Monaco", "Monaco"},
	MD: {"Moldova", "Moldova"},
	ME: {"Montenegro", "Montenegro"},
	MF: {"Saint Martin", "Saint-Martin"},
	MG: {"Madagascar", "Madagaskar"},
	MH: {"Marshall Islands", "Marshalløyene"},
	MK: {"North Macedonia", "Nord-Makedonia"},
	ML: {"Mali", "Mali"},
	MM: {"Myanmar", "Myanmar"},
	MN: {"Mongolia", "Mongolia"},
	MO: {"Macau", "Macao"},
	MP: {"Northern Mariana Islands", "Nord-Marianene"},
	MQ: {"Martinique", "Martinique"},
	MR: {"Mauritania", "Mauritania"},
	MS: {"Montserrat", "Montserrat"},
	MT: {"Malta", "Malta"},
	MU: {"Mauritius", "Mauritius"},
	MV: {"Maldives", "Maldivene"},
	MW: {"Malawi", "Malawi"},
	MX: {"Mexico", "Mexico"},
	MY: {"Malaysia", "Malaysia"},
	MZ: {"Mozambique", "Mosambik"},
	NA: {"Namibia", "Namibia"},
	NC: {"New Caledonia", "Ny-Caledonia"},
	NE: {"Niger", "Niger"},
	NF: {"Norfolk Island", "Norfolkøya"},
	NG: {"Nigeria", "Nigeria"},
	NI: {"Nicaragua", "Nicaragua"},
	NL: {"Netherlands", "Nederland"},
	NO: {"Norway", "Norge"},
	NP: {"Nepal", "Nepal"},
	NR: {"Nauru", "Nauru"},
	NU: {"Niue", "Niue"},
	NZ: {"New Zealand", "New Zealand"},
	OM: {"Oman", "Oman"},
	PA: {"Panama", "Panama"},
	PE: {"Peru", "Peru"},
	PF: {"French Polynesia", "Fransk Polynesia"},
	PG: {"Papua New Guinea", "Papua Ny-Guinea"},
	PH: {"Philippines", "Filippinene"},
	PK: {"Pakistan", "Pakistan"},
	PL: {"Poland", "Polen"},
	PM: {"Saint Pierre and Miquelon", "Saint-Pierre og Miquelon"},
	PN: {"Pitcairn Islands", "Pitcairnøyene"},
	PR: {"Puerto Rico", "Puerto Rico"},
	PS: {"State of Palestine", "Palestina"},
	PT: {"Portugal", "Portugal"},
	PW: {"Palau", "Palau"},
	PY: {"Paraguay", "Paraguay"},
	QA: {"Qatar", "Qatar"},
	RE: {"Réunion", "Réunion"},
	RO: {"Romania", "Romania"},
	RS: {"Serbia", "Serbia"},
	RU: {"Russia", "Russland"},
	RW: {"Rwanda", "Rwanda"},
	SA: {"Saudi Arabia", "Saudi-Arabia"},
	SB: {"Solomon Islands", "Salomonøyene"},
	SC: {"Seychelles", "Seychellene"},
	SD: {"Sudan", "Sudan"},
	SE: {"Sweden", "Sverige"},
	SG: {"Singapore", "Singapore"},
	SH: {"Saint Helena, Ascension and Tristan da Cunha", "Saint Helena, Ascension og Tristan da Cunha"},
	SI: {"Slovenia", "Slovenia"},
	SJ: {"Svalbard and Jan Mayen", "Svalbard og Jan Mayen"},
	SK: {"Slovakia", "Slovakia"},
	SL: {"Sierra Leone", "Sierra Leone"},
	SM: {"San Marino", "San Marino"},
	SN: {"Senegal", "Senegal"},
	SO: {"Somalia", "Somalia"},
	SR: {"Suriname", "Surinam"},
	SS: {"South Sudan", "Sør-Sudan"},
	ST: {"São Tomé and Príncipe", "São Tomé og Príncipe"},
	SV: {"El Salvador", "El Salvador"},
	SX: {"Sint Maarten", "Sint Maarten"},
	SY: {"Syria", "Syria"},
	SZ: {"Eswatini", "Eswatini"},
	TC: {"Turks and Caicos Islands", "Turks- og Caicosøyene"},
	TD: {"Chad", "Tsjad"},
	TF: {"French Southern and Antarctic Lands", "De franske sørterritorier"},
	TG: {"Togo", "Togo"},
	TH: {"Thailand", "Thailand"},
	TJ: {"Tajikistan", "Tadsjikistan"},
	TK: {"Tokelau", "Tokelau"},
	TL: {"East Timor", "Øst-Timor"},
	TM: {"Turkmenistan", "Turkmenistan"},
	TN: {"Tunisia", "Tunisia"},
	TO: {"Tonga", "Tonga"},
	TR: {"Turkey", "Tyrkia"},
	TT: {"Trinidad and Tobago", "Trinidad og Tobago"},
	TV: {"Tuvalu", "Tuvalu"},
	TW: {"Taiwan", "Taiwan"},
	TZ: {"Tanzania", "Tanzania"},
	UA: {"Ukraine", "Ukraina"},
	UG: {"Uganda", "Uganda"},
	UM: {"United States Minor Outlying Islands", "USAs ytre småøyer"},
	US: {"United States of America", "USA"},
	UY: {"Uruguay", "Uruguay"},
	UZ: {"Uzbekistan", "Usbekistan"},
	VA: {"Vatican City", "Vatikanstaten"},
	VC: {"Saint Vincent and the Grenadines", "Saint Vincent og Grenadinene"},
	VE: {"Venezuela", "Venezuela"},
	VG: {"British Virgin Islands", "De britiske Jomfruøyer"},
	VI: {"United States Virgin Islands", "De amerikanske Jomfruøyer"},
	VN: {"Vietnam", "Vietnam"},
	VU: {"Vanuatu", "Vanuatu"},
	WF: {"Wallis and Futuna", "Wallis- og Futunaøyene"},
	WS: {"Samoa", "Samoa"},
	XK: {"Kosovo", "Kosovo"},
	YE: {"Yemen", "Jemen"},
	YT: {"Mayotte", "Mayotte"},
	YU: {"Yugoslavia", "Jugoslavia"},
	ZA: {"South Africa", "Sør-Afrika"},
	ZM: {"Zambia", "Zambia"},
	ZW: {"Zimbabwe", "Zimbabwe"},
}

var allCodes = []Country{
	AD, AE, AF, AG, AI, AL, AM, AO, AQ, AR, AS, AT, AU, AW, AX, AZ, BA, BB, BD, BE,
	BF, BG, BH, BI, BJ, BL, BM, BN, BO, BQ, BR, BS, BT, BV, BW, BY, BZ, CA, CC, CD,
	CF, CG, CH, CI, CK, CL, CM, CN, CO, CR, CU, CV, CW, CX, CY, CZ, DE, DG, DJ, DK,
	DM, DO, DZ, EA, EC, EE, EG, EH, ER, ES, ET, FI, FJ, FK, FM, FO, FR, GA, GB, GD,
	GE, GF, GG, GH, GI, GL, GM, GN, GP, GQ, GR, GS, GT, GU, GW, GY, HK, HM, HN, HR,
	HT, HU, ID, IE, IL, IM, IN, IO, IQ, IR, IS, IT, JE, JM, JO, JP, KE, KG, KH, KI,
	KM, KN, KP, KR, KW, KY, KZ, LA, LB, LC, LI, LK, LR, LS, LT, LU, LV, LY, MA, MC,
	MD, ME, MF, MG, MH, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY,
	MZ, NA, NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, OM, PA, PE, PF, PG, PH, PK,
	PL, PM, PN, PR, PS, PT, PW, PY, QA, RE, RO, RS, RU, RW, SA, SB, SC, SD, SE, SG,
	SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, TC, TD, TF, TG, TH,
	TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, UA, UG, UM, US, UY, UZ, VA, VC, VE,
	VG, VI, VN, VU, WF, WS, XK, YE, YT, YU, ZA, ZM, ZW,
}

func ParseAlpha2(s string) (Country, error) {
	s = strings.ToUpper(s)
	if _, ok := alpha2Labels[Country(s)]; ok {
		return Country(s), nil
	}
	return "", vocab.ErrUnknown
}

// Code returns the ISO 3166-1 alpha-2 code.
func (a Country) Code() string {
	return string(a)
}

func (a Country) URI() string {
	return "iso3166/" + string(a)
}

// Label returns a string representation of the Alpha2 country in the desired language.
func (a Country) Label(tag language.Tag) string {
	match, _, _ := localizer.Matcher.Match(tag)
	if match == language.Norwegian {
		return alpha2Labels[a][1]
	}
	return alpha2Labels[a][0]
}

func Options(lang language.Tag) (res [][2]string) {
	match, _, _ := localizer.Matcher.Match(lang)
	i := 0
	if match == language.Norwegian {
		i = 1
	}
	for _, c := range allCodes {
		res = append(res, [2]string{string(c), alpha2Labels[c][i]})
	}
	return res
}
