// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2022-03-07T13:16:17+01:00
// using data from https://www.wikidata.org
package iso3166

import (
	"golang.org/x/text/language"
	"strings"

	"github.com/knakk/sirkulator/internal/localizer"
	"github.com/knakk/sirkulator/vocab"
)

//go:generate go run gen_alpha2.go
//go:generate go fmt alpha2.go

// Alpha2 is an ISO 3166-1 two-letter code, maintained by ublished by the International Organization
// for Standardization (ISO), to represent countries, dependent territories, and special areas of
// geographical interest.
// https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
type Alpha2 string

const (
	AD Alpha2 = "AD"
	AE Alpha2 = "AE"
	AF Alpha2 = "AF"
	AG Alpha2 = "AG"
	AI Alpha2 = "AI"
	AL Alpha2 = "AL"
	AM Alpha2 = "AM"
	AO Alpha2 = "AO"
	AQ Alpha2 = "AQ"
	AR Alpha2 = "AR"
	AS Alpha2 = "AS"
	AT Alpha2 = "AT"
	AU Alpha2 = "AU"
	AW Alpha2 = "AW"
	AX Alpha2 = "AX"
	AZ Alpha2 = "AZ"
	BA Alpha2 = "BA"
	BB Alpha2 = "BB"
	BD Alpha2 = "BD"
	BE Alpha2 = "BE"
	BF Alpha2 = "BF"
	BG Alpha2 = "BG"
	BH Alpha2 = "BH"
	BI Alpha2 = "BI"
	BJ Alpha2 = "BJ"
	BL Alpha2 = "BL"
	BM Alpha2 = "BM"
	BN Alpha2 = "BN"
	BO Alpha2 = "BO"
	BQ Alpha2 = "BQ"
	BR Alpha2 = "BR"
	BS Alpha2 = "BS"
	BT Alpha2 = "BT"
	BV Alpha2 = "BV"
	BW Alpha2 = "BW"
	BY Alpha2 = "BY"
	BZ Alpha2 = "BZ"
	CA Alpha2 = "CA"
	CC Alpha2 = "CC"
	CD Alpha2 = "CD"
	CF Alpha2 = "CF"
	CG Alpha2 = "CG"
	CH Alpha2 = "CH"
	CI Alpha2 = "CI"
	CK Alpha2 = "CK"
	CL Alpha2 = "CL"
	CM Alpha2 = "CM"
	CN Alpha2 = "CN"
	CO Alpha2 = "CO"
	CR Alpha2 = "CR"
	CU Alpha2 = "CU"
	CV Alpha2 = "CV"
	CW Alpha2 = "CW"
	CX Alpha2 = "CX"
	CY Alpha2 = "CY"
	CZ Alpha2 = "CZ"
	DE Alpha2 = "DE"
	DG Alpha2 = "DG"
	DJ Alpha2 = "DJ"
	DK Alpha2 = "DK"
	DM Alpha2 = "DM"
	DO Alpha2 = "DO"
	DZ Alpha2 = "DZ"
	EA Alpha2 = "EA"
	EC Alpha2 = "EC"
	EE Alpha2 = "EE"
	EG Alpha2 = "EG"
	EH Alpha2 = "EH"
	ER Alpha2 = "ER"
	ES Alpha2 = "ES"
	ET Alpha2 = "ET"
	FI Alpha2 = "FI"
	FJ Alpha2 = "FJ"
	FK Alpha2 = "FK"
	FM Alpha2 = "FM"
	FO Alpha2 = "FO"
	FR Alpha2 = "FR"
	GA Alpha2 = "GA"
	GB Alpha2 = "GB"
	GD Alpha2 = "GD"
	GE Alpha2 = "GE"
	GF Alpha2 = "GF"
	GG Alpha2 = "GG"
	GH Alpha2 = "GH"
	GI Alpha2 = "GI"
	GL Alpha2 = "GL"
	GM Alpha2 = "GM"
	GN Alpha2 = "GN"
	GP Alpha2 = "GP"
	GQ Alpha2 = "GQ"
	GR Alpha2 = "GR"
	GS Alpha2 = "GS"
	GT Alpha2 = "GT"
	GU Alpha2 = "GU"
	GW Alpha2 = "GW"
	GY Alpha2 = "GY"
	HK Alpha2 = "HK"
	HM Alpha2 = "HM"
	HN Alpha2 = "HN"
	HR Alpha2 = "HR"
	HT Alpha2 = "HT"
	HU Alpha2 = "HU"
	ID Alpha2 = "ID"
	IE Alpha2 = "IE"
	IL Alpha2 = "IL"
	IM Alpha2 = "IM"
	IN Alpha2 = "IN"
	IO Alpha2 = "IO"
	IQ Alpha2 = "IQ"
	IR Alpha2 = "IR"
	IS Alpha2 = "IS"
	IT Alpha2 = "IT"
	JE Alpha2 = "JE"
	JM Alpha2 = "JM"
	JO Alpha2 = "JO"
	JP Alpha2 = "JP"
	KE Alpha2 = "KE"
	KG Alpha2 = "KG"
	KH Alpha2 = "KH"
	KI Alpha2 = "KI"
	KM Alpha2 = "KM"
	KN Alpha2 = "KN"
	KP Alpha2 = "KP"
	KR Alpha2 = "KR"
	KW Alpha2 = "KW"
	KY Alpha2 = "KY"
	KZ Alpha2 = "KZ"
	LA Alpha2 = "LA"
	LB Alpha2 = "LB"
	LC Alpha2 = "LC"
	LI Alpha2 = "LI"
	LK Alpha2 = "LK"
	LR Alpha2 = "LR"
	LS Alpha2 = "LS"
	LT Alpha2 = "LT"
	LU Alpha2 = "LU"
	LV Alpha2 = "LV"
	LY Alpha2 = "LY"
	MA Alpha2 = "MA"
	MC Alpha2 = "MC"
	MD Alpha2 = "MD"
	ME Alpha2 = "ME"
	MF Alpha2 = "MF"
	MG Alpha2 = "MG"
	MH Alpha2 = "MH"
	MK Alpha2 = "MK"
	ML Alpha2 = "ML"
	MM Alpha2 = "MM"
	MN Alpha2 = "MN"
	MO Alpha2 = "MO"
	MP Alpha2 = "MP"
	MQ Alpha2 = "MQ"
	MR Alpha2 = "MR"
	MS Alpha2 = "MS"
	MT Alpha2 = "MT"
	MU Alpha2 = "MU"
	MV Alpha2 = "MV"
	MW Alpha2 = "MW"
	MX Alpha2 = "MX"
	MY Alpha2 = "MY"
	MZ Alpha2 = "MZ"
	NA Alpha2 = "NA"
	NC Alpha2 = "NC"
	NE Alpha2 = "NE"
	NF Alpha2 = "NF"
	NG Alpha2 = "NG"
	NI Alpha2 = "NI"
	NL Alpha2 = "NL"
	NO Alpha2 = "NO"
	NP Alpha2 = "NP"
	NR Alpha2 = "NR"
	NU Alpha2 = "NU"
	NZ Alpha2 = "NZ"
	OM Alpha2 = "OM"
	PA Alpha2 = "PA"
	PE Alpha2 = "PE"
	PF Alpha2 = "PF"
	PG Alpha2 = "PG"
	PH Alpha2 = "PH"
	PK Alpha2 = "PK"
	PL Alpha2 = "PL"
	PM Alpha2 = "PM"
	PN Alpha2 = "PN"
	PR Alpha2 = "PR"
	PS Alpha2 = "PS"
	PT Alpha2 = "PT"
	PW Alpha2 = "PW"
	PY Alpha2 = "PY"
	QA Alpha2 = "QA"
	RE Alpha2 = "RE"
	RO Alpha2 = "RO"
	RS Alpha2 = "RS"
	RU Alpha2 = "RU"
	RW Alpha2 = "RW"
	SA Alpha2 = "SA"
	SB Alpha2 = "SB"
	SC Alpha2 = "SC"
	SD Alpha2 = "SD"
	SE Alpha2 = "SE"
	SG Alpha2 = "SG"
	SH Alpha2 = "SH"
	SI Alpha2 = "SI"
	SJ Alpha2 = "SJ"
	SK Alpha2 = "SK"
	SL Alpha2 = "SL"
	SM Alpha2 = "SM"
	SN Alpha2 = "SN"
	SO Alpha2 = "SO"
	SR Alpha2 = "SR"
	SS Alpha2 = "SS"
	ST Alpha2 = "ST"
	SV Alpha2 = "SV"
	SX Alpha2 = "SX"
	SY Alpha2 = "SY"
	SZ Alpha2 = "SZ"
	TC Alpha2 = "TC"
	TD Alpha2 = "TD"
	TF Alpha2 = "TF"
	TG Alpha2 = "TG"
	TH Alpha2 = "TH"
	TJ Alpha2 = "TJ"
	TK Alpha2 = "TK"
	TL Alpha2 = "TL"
	TM Alpha2 = "TM"
	TN Alpha2 = "TN"
	TO Alpha2 = "TO"
	TR Alpha2 = "TR"
	TT Alpha2 = "TT"
	TV Alpha2 = "TV"
	TW Alpha2 = "TW"
	TZ Alpha2 = "TZ"
	UA Alpha2 = "UA"
	UG Alpha2 = "UG"
	UM Alpha2 = "UM"
	US Alpha2 = "US"
	UY Alpha2 = "UY"
	UZ Alpha2 = "UZ"
	VA Alpha2 = "VA"
	VC Alpha2 = "VC"
	VE Alpha2 = "VE"
	VG Alpha2 = "VG"
	VI Alpha2 = "VI"
	VN Alpha2 = "VN"
	VU Alpha2 = "VU"
	WF Alpha2 = "WF"
	WS Alpha2 = "WS"
	XK Alpha2 = "XK"
	YE Alpha2 = "YE"
	YT Alpha2 = "YT"
	YU Alpha2 = "YU"
	ZA Alpha2 = "ZA"
	ZM Alpha2 = "ZM"
	ZW Alpha2 = "ZW"
)

var alpha2Labels = map[Alpha2][2]string{
	AD: {"Andorra", "Andorra"},
	AE: {"United Arab Emirates", "De forente arabiske emirater"},
	AF: {"Afghanistan", "Afghanistan"},
	AG: {"Antigua and Barbuda", "Antigua og Barbuda"},
	AI: {"Anguilla", "Anguilla"},
	AL: {"Albania", "Albania"},
	AM: {"Armenia", "Armenia"},
	AO: {"Angola", "Angola"},
	AQ: {"Antarctic Treaty area", "Antarktistraktatsområdet"},
	AR: {"Argentina", "Argentina"},
	AS: {"American Samoa", "Amerikansk Samoa"},
	AT: {"Austria", "Østerrike"},
	AU: {"Australia", "Australia"},
	AW: {"Aruba", "Aruba"},
	AX: {"Åland", "Åland"},
	AZ: {"Azerbaijan", "Aserbajdsjan"},
	BA: {"Bosnia and Herzegovina", "Bosnia-Hercegovina"},
	BB: {"Barbados", "Barbados"},
	BD: {"Bangladesh", "Bangladesh"},
	BE: {"Belgium", "Belgia"},
	BF: {"Burkina Faso", "Burkina Faso"},
	BG: {"Bulgaria", "Bulgaria"},
	BH: {"Bahrain", "Bahrain"},
	BI: {"Burundi", "Burundi"},
	BJ: {"Benin", "Benin"},
	BL: {"Saint Barthélemy", "Saint-Barthélemy"},
	BM: {"Bermuda", "Bermuda"},
	BN: {"Brunei", "Brunei"},
	BO: {"Bolivia", "Bolivia"},
	BQ: {"Caribbean Netherlands", "Karibisk Nederland"},
	BR: {"Brazil", "Brasil"},
	BS: {"The Bahamas", "Bahamas"},
	BT: {"Bhutan", "Bhutan"},
	BV: {"Bouvet Island", "Bouvetøya"},
	BW: {"Botswana", "Botswana"},
	BY: {"Belarus", "Hviterussland"},
	BZ: {"Belize", "Belize"},
	CA: {"Canada", "Canada"},
	CC: {"Cocos (Keeling) Islands", "Kokosøyene"},
	CD: {"Democratic Republic of the Congo", "Den demokratiske republikken Kongo"},
	CF: {"Central African Republic", "Den sentralafrikanske republikk"},
	CG: {"Republic of the Congo", "Republikken Kongo"},
	CH: {"Switzerland", "Sveits"},
	CI: {"Côte d'Ivoire", "Elfenbenskysten"},
	CK: {"Cook Islands", "Cookøyene"},
	CL: {"Chile", "Chile"},
	CM: {"Cameroon", "Kamerun"},
	CN: {"People's Republic of China", "Kina"},
	CO: {"Colombia", "Colombia"},
	CR: {"Costa Rica", "Costa Rica"},
	CU: {"Cuba", "Cuba"},
	CV: {"Cape Verde", "Kapp Verde"},
	CW: {"Curaçao", "Curaçao"},
	CX: {"Christmas Island", "Christmasøya"},
	CY: {"Cyprus", "Kypros"},
	CZ: {"Czech Republic", "Tsjekkia"},
	DE: {"Germany", "Tyskland"},
	DG: {"Diego Garcia", "Diego Garcia"},
	DJ: {"Djibouti", "Djibouti"},
	DK: {"Denmark", "Danmark"},
	DM: {"Dominica", "Dominica"},
	DO: {"Dominican Republic", "Den dominikanske republikk"},
	DZ: {"Algeria", "Algerie"},
	EA: {"Ceuta and Melilla", "Ceuta og Melilla"},
	EC: {"Ecuador", "Ecuador"},
	EE: {"Estonia", "Estland"},
	EG: {"Egypt", "Egypt"},
	EH: {"Western Sahara", "Vest-Sahara"},
	ER: {"Eritrea", "Eritrea"},
	ES: {"Spain", "Spania"},
	ET: {"Ethiopia", "Etiopia"},
	FI: {"Finland", "Finland"},
	FJ: {"Fiji", "Fiji"},
	FK: {"Falkland Islands", "Falklandsøyene"},
	FM: {"Federated States of Micronesia", "Mikronesiaføderasjonen"},
	FO: {"Faroe Islands", "Færøyene"},
	FR: {"France", "Frankrike"},
	GA: {"Gabon", "Gabon"},
	GB: {"United Kingdom", "Storbritannia"},
	GD: {"Grenada", "Grenada"},
	GE: {"Georgia", "Georgia"},
	GF: {"French Guiana", "Fransk Guyana"},
	GG: {"Guernsey", "Guernsey"},
	GH: {"Ghana", "Ghana"},
	GI: {"Gibraltar", "Gibraltar"},
	GL: {"Greenland", "Grønland"},
	GM: {"The Gambia", "Gambia"},
	GN: {"Guinea", "Guinea"},
	GP: {"Guadeloupe", "Guadeloupe"},
	GQ: {"Equatorial Guinea", "Ekvatorial-Guinea"},
	GR: {"Greece", "Hellas"},
	GS: {"South Georgia and the South Sandwich Islands", "Sør-Georgia og Sør-Sandwichøyene"},
	GT: {"Guatemala", "Guatemala"},
	GU: {"Guam", "Guam"},
	GW: {"Guinea-Bissau", "Guinea-Bissau"},
	GY: {"Guyana", "Guyana"},
	HK: {"Hong Kong", "Hongkong"},
	HM: {"Heard Island and McDonald Islands", "Heard- og McDonaldøyene"},
	HN: {"Honduras", "Honduras"},
	HR: {"Croatia", "Kroatia"},
	HT: {"Haiti", "Haiti"},
	HU: {"Hungary", "Ungarn"},
	ID: {"Indonesia", "Indonesia"},
	IE: {"Republic of Ireland", "Irland"},
	IL: {"Israel", "Israel"},
	IM: {"Isle of Man", "Man"},
	IN: {"India", "India"},
	IO: {"British Indian Ocean Territory", "Det britiske territoriet i Indiahavet"},
	IQ: {"Iraq", "Irak"},
	IR: {"Iran", "Iran"},
	IS: {"Iceland", "Island"},
	IT: {"Italy", "Italia"},
	JE: {"Jersey", "Jersey"},
	JM: {"Jamaica", "Jamaica"},
	JO: {"Jordan", "Jordan"},
	JP: {"Japan", "Japan"},
	KE: {"Kenya", "Kenya"},
	KG: {"Kyrgyzstan", "Kirgisistan"},
	KH: {"Cambodia", "Kambodsja"},
	KI: {"Kiribati", "Kiribati"},
	KM: {"Comoros", "Komorene"},
	KN: {"Saint Kitts and Nevis", "Saint Kitts og Nevis"},
	KP: {"North Korea", "Nord-Korea"},
	KR: {"South Korea", "Sør-Korea"},
	KW: {"Kuwait", "Kuwait"},
	KY: {"Cayman Islands", "Caymanøyene"},
	KZ: {"Kazakhstan", "Kasakhstan"},
	LA: {"Laos", "Laos"},
	LB: {"Lebanon", "Libanon"},
	LC: {"Saint Lucia", "Saint Lucia"},
	LI: {"Liechtenstein", "Liechtenstein"},
	LK: {"Sri Lanka", "Sri Lanka"},
	LR: {"Liberia", "Liberia"},
	LS: {"Lesotho", "Lesotho"},
	LT: {"Lithuania", "Litauen"},
	LU: {"Luxembourg", "Luxembourg"},
	LV: {"Latvia", "Latvia"},
	LY: {"Libya", "Libya"},
	MA: {"Morocco", "Marokko"},
	MC: {"Monaco", "Monaco"},
	MD: {"Moldova", "Moldova"},
	ME: {"Montenegro", "Montenegro"},
	MF: {"Saint Martin", "Saint-Martin"},
	MG: {"Madagascar", "Madagaskar"},
	MH: {"Marshall Islands", "Marshalløyene"},
	MK: {"North Macedonia", "Nord-Makedonia"},
	ML: {"Mali", "Mali"},
	MM: {"Myanmar", "Myanmar"},
	MN: {"Mongolia", "Mongolia"},
	MO: {"Macau", "Macao"},
	MP: {"Northern Mariana Islands", "Nord-Marianene"},
	MQ: {"Martinique", "Martinique"},
	MR: {"Mauritania", "Mauritania"},
	MS: {"Montserrat", "Montserrat"},
	MT: {"Malta", "Malta"},
	MU: {"Mauritius", "Mauritius"},
	MV: {"Maldives", "Maldivene"},
	MW: {"Malawi", "Malawi"},
	MX: {"Mexico", "Mexico"},
	MY: {"Malaysia", "Malaysia"},
	MZ: {"Mozambique", "Mosambik"},
	NA: {"Namibia", "Namibia"},
	NC: {"New Caledonia", "Ny-Caledonia"},
	NE: {"Niger", "Niger"},
	NF: {"Norfolk Island", "Norfolkøya"},
	NG: {"Nigeria", "Nigeria"},
	NI: {"Nicaragua", "Nicaragua"},
	NL: {"Netherlands", "Nederland"},
	NO: {"Norway", "Norge"},
	NP: {"Nepal", "Nepal"},
	NR: {"Nauru", "Nauru"},
	NU: {"Niue", "Niue"},
	NZ: {"New Zealand", "New Zealand"},
	OM: {"Oman", "Oman"},
	PA: {"Panama", "Panama"},
	PE: {"Peru", "Peru"},
	PF: {"French Polynesia", "Fransk Polynesia"},
	PG: {"Papua New Guinea", "Papua Ny-Guinea"},
	PH: {"Philippines", "Filippinene"},
	PK: {"Pakistan", "Pakistan"},
	PL: {"Poland", "Polen"},
	PM: {"Saint Pierre and Miquelon", "Saint-Pierre og Miquelon"},
	PN: {"Pitcairn Islands", "Pitcairnøyene"},
	PR: {"Puerto Rico", "Puerto Rico"},
	PS: {"State of Palestine", "Palestina"},
	PT: {"Portugal", "Portugal"},
	PW: {"Palau", "Palau"},
	PY: {"Paraguay", "Paraguay"},
	QA: {"Qatar", "Qatar"},
	RE: {"Réunion", "Réunion"},
	RO: {"Romania", "Romania"},
	RS: {"Serbia", "Serbia"},
	RU: {"Russia", "Russland"},
	RW: {"Rwanda", "Rwanda"},
	SA: {"Saudi Arabia", "Saudi-Arabia"},
	SB: {"Solomon Islands", "Salomonøyene"},
	SC: {"Seychelles", "Seychellene"},
	SD: {"Sudan", "Sudan"},
	SE: {"Sweden", "Sverige"},
	SG: {"Singapore", "Singapore"},
	SH: {"Saint Helena, Ascension and Tristan da Cunha", "Saint Helena, Ascension og Tristan da Cunha"},
	SI: {"Slovenia", "Slovenia"},
	SJ: {"Svalbard and Jan Mayen", "Svalbard og Jan Mayen"},
	SK: {"Slovakia", "Slovakia"},
	SL: {"Sierra Leone", "Sierra Leone"},
	SM: {"San Marino", "San Marino"},
	SN: {"Senegal", "Senegal"},
	SO: {"Somalia", "Somalia"},
	SR: {"Suriname", "Surinam"},
	SS: {"South Sudan", "Sør-Sudan"},
	ST: {"São Tomé and Príncipe", "São Tomé og Príncipe"},
	SV: {"El Salvador", "El Salvador"},
	SX: {"Sint Maarten", "Sint Maarten"},
	SY: {"Syria", "Syria"},
	SZ: {"Eswatini", "Eswatini"},
	TC: {"Turks and Caicos Islands", "Turks- og Caicosøyene"},
	TD: {"Chad", "Tsjad"},
	TF: {"French Southern and Antarctic Lands", "De franske sørterritorier"},
	TG: {"Togo", "Togo"},
	TH: {"Thailand", "Thailand"},
	TJ: {"Tajikistan", "Tadsjikistan"},
	TK: {"Tokelau", "Tokelau"},
	TL: {"East Timor", "Øst-Timor"},
	TM: {"Turkmenistan", "Turkmenistan"},
	TN: {"Tunisia", "Tunisia"},
	TO: {"Tonga", "Tonga"},
	TR: {"Turkey", "Tyrkia"},
	TT: {"Trinidad and Tobago", "Trinidad og Tobago"},
	TV: {"Tuvalu", "Tuvalu"},
	TW: {"Taiwan", "Taiwan"},
	TZ: {"Tanzania", "Tanzania"},
	UA: {"Ukraine", "Ukraina"},
	UG: {"Uganda", "Uganda"},
	UM: {"United States Minor Outlying Islands", "USAs ytre småøyer"},
	US: {"United States of America", "USA"},
	UY: {"Uruguay", "Uruguay"},
	UZ: {"Uzbekistan", "Usbekistan"},
	VA: {"Vatican City", "Vatikanstaten"},
	VC: {"Saint Vincent and the Grenadines", "Saint Vincent og Grenadinene"},
	VE: {"Venezuela", "Venezuela"},
	VG: {"British Virgin Islands", "De britiske Jomfruøyer"},
	VI: {"United States Virgin Islands", "De amerikanske Jomfruøyer"},
	VN: {"Vietnam", "Vietnam"},
	VU: {"Vanuatu", "Vanuatu"},
	WF: {"Wallis and Futuna", "Wallis- og Futunaøyene"},
	WS: {"Samoa", "Samoa"},
	XK: {"Kosovo", "Kosovo"},
	YE: {"Yemen", "Jemen"},
	YT: {"Mayotte", "Mayotte"},
	YU: {"Yugoslavia", "Jugoslavia"},
	ZA: {"South Africa", "Sør-Afrika"},
	ZM: {"Zambia", "Zambia"},
	ZW: {"Zimbabwe", "Zimbabwe"},
}

var allCodes = []Alpha2{
	AD, AE, AF, AG, AI, AL, AM, AO, AQ, AR, AS, AT, AU, AW, AX, AZ, BA, BB, BD, BE,
	BF, BG, BH, BI, BJ, BL, BM, BN, BO, BQ, BR, BS, BT, BV, BW, BY, BZ, CA, CC, CD,
	CF, CG, CH, CI, CK, CL, CM, CN, CO, CR, CU, CV, CW, CX, CY, CZ, DE, DG, DJ, DK,
	DM, DO, DZ, EA, EC, EE, EG, EH, ER, ES, ET, FI, FJ, FK, FM, FO, FR, GA, GB, GD,
	GE, GF, GG, GH, GI, GL, GM, GN, GP, GQ, GR, GS, GT, GU, GW, GY, HK, HM, HN, HR,
	HT, HU, ID, IE, IL, IM, IN, IO, IQ, IR, IS, IT, JE, JM, JO, JP, KE, KG, KH, KI,
	KM, KN, KP, KR, KW, KY, KZ, LA, LB, LC, LI, LK, LR, LS, LT, LU, LV, LY, MA, MC,
	MD, ME, MF, MG, MH, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY,
	MZ, NA, NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, OM, PA, PE, PF, PG, PH, PK,
	PL, PM, PN, PR, PS, PT, PW, PY, QA, RE, RO, RS, RU, RW, SA, SB, SC, SD, SE, SG,
	SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, TC, TD, TF, TG, TH,
	TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, UA, UG, UM, US, UY, UZ, VA, VC, VE,
	VG, VI, VN, VU, WF, WS, XK, YE, YT, YU, ZA, ZM, ZW,
}

func ParseAlpha2(s string) (Alpha2, error) {
	s = strings.ToUpper(s)
	if _, ok := alpha2Labels[Alpha2(s)]; ok {
		return Alpha2(s), nil
	}
	return "", vocab.ErrUnknown
}

// Code returns the ISO 3166-1 alpha-2 code.
func (a Alpha2) Code() string {
	return string(a)
}

func (a Alpha2) URI() string {
	return "iso3166/" + string(a)
}

// Label returns a string representation of the Alpha2 country in the desired language.
func (a Alpha2) Label(tag language.Tag) string {
	match, _, _ := localizer.Matcher.Match(tag)
	if match == language.Norwegian {
		return alpha2Labels[a][1]
	}
	return alpha2Labels[a][0]
}

func Options(lang language.Tag) (res [][2]string) {
	match, _, _ := localizer.Matcher.Match(lang)
	i := 0
	if match == language.Norwegian {
		i = 1
	}
	for _, c := range allCodes {
		res = append(res, [2]string{string(c), alpha2Labels[c][i]})
	}
	return res
}
