// Code generated by go generate; DO NOT EDIT.
// This file was generated at 2022-02-10T19:26:31+01:00
// using data from the RDA Registry maintained by the RDA Steering Committee (http://www.rda-rsc.org/)
package rda

import (
	"github.com/knakk/sirkulator/internal/localizer"
	"github.com/knakk/sirkulator/vocab"
	"golang.org/x/text/language"
)

//go:generate go run gen_codes.go

var labelsMT = map[string][2]string{
	"1001": {"audio", "lydmedier"},
	"1003": {"computer", "datamaskin"},
	"1002": {"microform", "mikroform"},
	"1004": {"microscopic", "mikroskopisk"},
	"1005": {"projected", "projisert"},
	"1006": {"stereographic", "stereografisk"},
	"1007": {"unmediated", "uformidlet"},
	"1008": {"video", "video"},
}

var deprecatedMT = map[string]string{}

// MT is a RDA Term Code.
type MT string

func (t MT) Code() string {
	return string(t)
}

func (t MT) URI() string {
	return "http://rdaregistry.info/termList/RDAMediaType/" + string(t)
}

func (t MT) Label(tag language.Tag) string {
	match, _, _ := localizer.Matcher.Match(tag)
	if match == language.Norwegian && labelsMT[string(t)][1] != "" {
		return labelsMT[string(t)][1]
	}
	return labelsMT[string(t)][0]
}

func ParseMT(s string) (MT, error) {
	if _, ok := labelsMT[s]; ok {
		return MT(s), nil
	}
	if _, ok := deprecatedMT[s]; ok {
		return MT("unknown"), vocab.ErrDeprecated
	}
	return MT("unknown"), vocab.ErrUnknown
}
